FROM python:3.6-slim

COPY requirements.txt requirements.txt
RUN pip install -r  requirements.txt

WORKDIR /work

COPY ./src /work/
ENV PYTHONPATH=/work/
ENV GPU=1
ENV DATA_SET=mnist
ENV GPU_MEMORY_FRACTION=1.0
CMD python applications/run.py --gpu=${GPU} --dset=${DATA_SET} --gpu_memory_fraction=${GPU_MEMORY_FRACTION}
